// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountUsers(ctx context.Context, arg CountUsersParams) (int64, error)
	CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExpiredPasswordResetTokens(ctx context.Context) (int64, error)
	DeleteUser(ctx context.Context, id uuid.UUID) (int64, error)
	EmailExists(ctx context.Context, email string) (bool, error)
	GetPasswordResetToken(ctx context.Context, tokenHash string) (PasswordResetToken, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	InvalidateUserPasswordResetTokens(ctx context.Context, userID uuid.UUID) error
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	MarkPasswordResetTokenUsed(ctx context.Context, id uuid.UUID) (int64, error)
	UpdateLastLogin(ctx context.Context, id uuid.UUID) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
