// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_verification_tokens.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createEmailVerificationToken = `-- name: CreateEmailVerificationToken :one
INSERT INTO email_verification_tokens (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expires_at, used_at, created_at
`

type CreateEmailVerificationTokenParams struct {
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt time.Time
}

func (q *Queries) CreateEmailVerificationToken(ctx context.Context, arg CreateEmailVerificationTokenParams) (EmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, createEmailVerificationToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i EmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredEmailVerificationTokens = `-- name: DeleteExpiredEmailVerificationTokens :execrows
DELETE FROM email_verification_tokens WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredEmailVerificationTokens(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredEmailVerificationTokens)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEmailVerificationToken = `-- name: GetEmailVerificationToken :one
SELECT id, user_id, token_hash, expires_at, used_at, created_at FROM email_verification_tokens WHERE token_hash = $1
`

func (q *Queries) GetEmailVerificationToken(ctx context.Context, tokenHash string) (EmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, getEmailVerificationToken, tokenHash)
	var i EmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const invalidateUserEmailVerificationTokens = `-- name: InvalidateUserEmailVerificationTokens :exec
UPDATE email_verification_tokens
SET used_at = NOW()
WHERE user_id = $1 AND used_at IS NULL
`

func (q *Queries) InvalidateUserEmailVerificationTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, invalidateUserEmailVerificationTokens, userID)
	return err
}

const markEmailVerificationTokenUsed = `-- name: MarkEmailVerificationTokenUsed :execrows
UPDATE email_verification_tokens
SET used_at = NOW()
WHERE id = $1 AND used_at IS NULL
`

func (q *Queries) MarkEmailVerificationTokenUsed(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markEmailVerificationTokenUsed, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
