// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth_accounts.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createOAuthUser = `-- name: CreateOAuthUser :one
INSERT INTO users (email, full_name, avatar_url, email_verified_at, role)
VALUES (
    $1,
    $2,
    $3::text,
    NOW(),
    'user'
)
RETURNING id, email, password_hash, full_name, role, avatar_url, is_active, email_verified_at, last_login_at, created_at, updated_at
`

type CreateOAuthUserParams struct {
	Email     string
	FullName  string
	AvatarUrl *string
}

// Registration through a provider. The password hash is deliberately absent:
// NULL means this account has no password to sign in with. The email arrives
// already verified by the provider, so email_verified_at is set here.
func (q *Queries) CreateOAuthUser(ctx context.Context, arg CreateOAuthUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createOAuthUser, arg.Email, arg.FullName, arg.AvatarUrl)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.AvatarUrl,
		&i.IsActive,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOAuthAccount = `-- name: GetOAuthAccount :one
SELECT id, user_id, provider, provider_account_id, email, created_at, updated_at FROM oauth_accounts
WHERE provider = $1 AND provider_account_id = $2
`

type GetOAuthAccountParams struct {
	Provider          string
	ProviderAccountID string
}

// Looks up a local account by the external identity. Keyed on the provider's
// stable subject id, never the email, which the person can change upstream.
func (q *Queries) GetOAuthAccount(ctx context.Context, arg GetOAuthAccountParams) (OauthAccount, error) {
	row := q.db.QueryRow(ctx, getOAuthAccount, arg.Provider, arg.ProviderAccountID)
	var i OauthAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderAccountID,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOAuthAccountsByUser = `-- name: GetOAuthAccountsByUser :many
SELECT id, user_id, provider, provider_account_id, email, created_at, updated_at FROM oauth_accounts
WHERE user_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetOAuthAccountsByUser(ctx context.Context, userID uuid.UUID) ([]OauthAccount, error) {
	rows, err := q.db.Query(ctx, getOAuthAccountsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OauthAccount{}
	for rows.Next() {
		var i OauthAccount
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.ProviderAccountID,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkOAuthAccount = `-- name: LinkOAuthAccount :one
INSERT INTO oauth_accounts (user_id, provider, provider_account_id, email)
VALUES ($1, $2, $3, $4::citext)
RETURNING id, user_id, provider, provider_account_id, email, created_at, updated_at
`

type LinkOAuthAccountParams struct {
	UserID            uuid.UUID
	Provider          string
	ProviderAccountID string
	Email             pgtype.Text
}

func (q *Queries) LinkOAuthAccount(ctx context.Context, arg LinkOAuthAccountParams) (OauthAccount, error) {
	row := q.db.QueryRow(ctx, linkOAuthAccount,
		arg.UserID,
		arg.Provider,
		arg.ProviderAccountID,
		arg.Email,
	)
	var i OauthAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderAccountID,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markEmailVerified = `-- name: MarkEmailVerified :one
UPDATE users
SET email_verified_at = COALESCE(email_verified_at, NOW())
WHERE id = $1
RETURNING id, email, password_hash, full_name, role, avatar_url, is_active, email_verified_at, last_login_at, created_at, updated_at
`

// Used when an existing password account is linked to a provider that has
// already verified the same address.
func (q *Queries) MarkEmailVerified(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, markEmailVerified, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.AvatarUrl,
		&i.IsActive,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setUserAvatarIfEmpty = `-- name: SetUserAvatarIfEmpty :one
UPDATE users
SET avatar_url = COALESCE(avatar_url, $2::text)
WHERE id = $1
RETURNING id, email, password_hash, full_name, role, avatar_url, is_active, email_verified_at, last_login_at, created_at, updated_at
`

type SetUserAvatarIfEmptyParams struct {
	ID        uuid.UUID
	AvatarUrl *string
}

// The provider's picture is only adopted when the person has not chosen one,
// so a later sign-in never overwrites an uploaded avatar.
func (q *Queries) SetUserAvatarIfEmpty(ctx context.Context, arg SetUserAvatarIfEmptyParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserAvatarIfEmpty, arg.ID, arg.AvatarUrl)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.AvatarUrl,
		&i.IsActive,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const unlinkOAuthAccount = `-- name: UnlinkOAuthAccount :execrows
DELETE FROM oauth_accounts
WHERE user_id = $1 AND provider = $2
`

type UnlinkOAuthAccountParams struct {
	UserID   uuid.UUID
	Provider string
}

func (q *Queries) UnlinkOAuthAccount(ctx context.Context, arg UnlinkOAuthAccountParams) (int64, error) {
	result, err := q.db.Exec(ctx, unlinkOAuthAccount, arg.UserID, arg.Provider)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateOAuthAccountEmail = `-- name: UpdateOAuthAccountEmail :one
UPDATE oauth_accounts
SET email = $3::citext
WHERE provider = $1 AND provider_account_id = $2
RETURNING id, user_id, provider, provider_account_id, email, created_at, updated_at
`

type UpdateOAuthAccountEmailParams struct {
	Provider          string
	ProviderAccountID string
	Email             pgtype.Text
}

// Keeps the recorded provider email current without touching the local one.
func (q *Queries) UpdateOAuthAccountEmail(ctx context.Context, arg UpdateOAuthAccountEmailParams) (OauthAccount, error) {
	row := q.db.QueryRow(ctx, updateOAuthAccountEmail, arg.Provider, arg.ProviderAccountID, arg.Email)
	var i OauthAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderAccountID,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
