// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: password_reset_tokens.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPasswordResetToken = `-- name: CreatePasswordResetToken :one
INSERT INTO password_reset_tokens (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expires_at, used_at, created_at
`

type CreatePasswordResetTokenParams struct {
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt time.Time
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, createPasswordResetToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredPasswordResetTokens = `-- name: DeleteExpiredPasswordResetTokens :execrows
DELETE FROM password_reset_tokens WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredPasswordResetTokens(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredPasswordResetTokens)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPasswordResetToken = `-- name: GetPasswordResetToken :one
SELECT id, user_id, token_hash, expires_at, used_at, created_at FROM password_reset_tokens WHERE token_hash = $1
`

func (q *Queries) GetPasswordResetToken(ctx context.Context, tokenHash string) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, getPasswordResetToken, tokenHash)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const invalidateUserPasswordResetTokens = `-- name: InvalidateUserPasswordResetTokens :exec
UPDATE password_reset_tokens
SET used_at = NOW()
WHERE user_id = $1 AND used_at IS NULL
`

func (q *Queries) InvalidateUserPasswordResetTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, invalidateUserPasswordResetTokens, userID)
	return err
}

const markPasswordResetTokenUsed = `-- name: MarkPasswordResetTokenUsed :execrows
UPDATE password_reset_tokens
SET used_at = NOW()
WHERE id = $1 AND used_at IS NULL
`

func (q *Queries) MarkPasswordResetTokenUsed(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markPasswordResetTokenUsed, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
