// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// Idempotent by design: adding a word already in the list is not an error, it
	// just returns the existing row untouched so the client can be naive about it.
	AddWordToUser(ctx context.Context, arg AddWordToUserParams) (UserWord, error)
	CountUserWords(ctx context.Context, arg CountUserWordsParams) (int64, error)
	CountUsers(ctx context.Context, arg CountUsersParams) (int64, error)
	CountWords(ctx context.Context, arg CountWordsParams) (int64, error)
	CreateEmailVerificationToken(ctx context.Context, arg CreateEmailVerificationTokenParams) (EmailVerificationToken, error)
	// Registration through a provider. The password hash is deliberately absent:
	// NULL means this account has no password to sign in with. The email arrives
	// already verified by the provider, so email_verified_at is set here.
	CreateOAuthUser(ctx context.Context, arg CreateOAuthUserParams) (User, error)
	CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWord(ctx context.Context, arg CreateWordParams) (Word, error)
	CreateWordSense(ctx context.Context, arg CreateWordSenseParams) (WordSense, error)
	DeleteExpiredEmailVerificationTokens(ctx context.Context) (int64, error)
	DeleteExpiredPasswordResetTokens(ctx context.Context) (int64, error)
	DeleteUser(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteWord(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteWordSense(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteWordSensesByWord(ctx context.Context, wordID uuid.UUID) error
	EmailExists(ctx context.Context, email string) (bool, error)
	GetEmailVerificationToken(ctx context.Context, tokenHash string) (EmailVerificationToken, error)
	// Looks up a local account by the external identity. Keyed on the provider's
	// stable subject id, never the email, which the person can change upstream.
	GetOAuthAccount(ctx context.Context, arg GetOAuthAccountParams) (OauthAccount, error)
	GetOAuthAccountsByUser(ctx context.Context, userID uuid.UUID) ([]OauthAccount, error)
	GetPasswordResetToken(ctx context.Context, tokenHash string) (PasswordResetToken, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserWord(ctx context.Context, arg GetUserWordParams) (UserWord, error)
	// Powers the progress header in one query rather than five counts.
	GetUserWordStats(ctx context.Context, userID uuid.UUID) (GetUserWordStatsRow, error)
	GetWord(ctx context.Context, id uuid.UUID) (Word, error)
	GetWordByTerm(ctx context.Context, arg GetWordByTermParams) (Word, error)
	GetWordSense(ctx context.Context, id uuid.UUID) (WordSense, error)
	InvalidateUserEmailVerificationTokens(ctx context.Context, userID uuid.UUID) error
	InvalidateUserPasswordResetTokens(ctx context.Context, userID uuid.UUID) error
	LinkOAuthAccount(ctx context.Context, arg LinkOAuthAccountParams) (OauthAccount, error)
	// The list view joins the catalogue so one round trip returns everything the
	// client renders. Column names are prefixed to keep them unambiguous in Go.
	ListUserWords(ctx context.Context, arg ListUserWordsParams) ([]ListUserWordsRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	ListWordSensesByWord(ctx context.Context, wordID uuid.UUID) ([]WordSense, error)
	// Powers word listing: one query for every sense of every word on the page,
	// instead of one round trip per word.
	ListWordSensesByWordIDs(ctx context.Context, wordIds []uuid.UUID) ([]WordSense, error)
	// Distinct tags with usage counts, for filter menus and autocomplete.
	ListWordTags(ctx context.Context, arg ListWordTagsParams) ([]ListWordTagsRow, error)
	ListWords(ctx context.Context, arg ListWordsParams) ([]Word, error)
	MarkEmailVerificationTokenUsed(ctx context.Context, id uuid.UUID) (int64, error)
	// Used when an existing password account is linked to a provider that has
	// already verified the same address.
	MarkEmailVerified(ctx context.Context, id uuid.UUID) (User, error)
	MarkPasswordResetTokenUsed(ctx context.Context, id uuid.UUID) (int64, error)
	MarkUserEmailVerified(ctx context.Context, id uuid.UUID) error
	// Leitner scheduling, done in one statement so the counters and the next due
	// date can never disagree. A correct answer promotes the card one box (max 5),
	// a wrong answer sends it back to box 0 for same-day repetition. Intervals are
	// 0d, 1d, 2d, 4d, 7d, 15d.
	RecordReview(ctx context.Context, arg RecordReviewParams) (UserWord, error)
	RemoveWordFromUser(ctx context.Context, arg RemoveWordFromUserParams) (int64, error)
	// The provider's picture is only adopted when the person has not chosen one,
	// so a later sign-in never overwrites an uploaded avatar.
	SetUserAvatarIfEmpty(ctx context.Context, arg SetUserAvatarIfEmptyParams) (User, error)
	UnlinkOAuthAccount(ctx context.Context, arg UnlinkOAuthAccountParams) (int64, error)
	UpdateLastLogin(ctx context.Context, id uuid.UUID) error
	// Keeps the recorded provider email current without touching the local one.
	UpdateOAuthAccountEmail(ctx context.Context, arg UpdateOAuthAccountEmailParams) (OauthAccount, error)
	// COALESCE lets a single statement act as a partial update: NULL means "leave
	// this column alone", so PATCH semantics need no dynamic SQL.
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserWord(ctx context.Context, arg UpdateUserWordParams) (UserWord, error)
	// Partial update: every field falls back to its current value, so a caller
	// sends only what changed.
	UpdateWord(ctx context.Context, arg UpdateWordParams) (Word, error)
	// Partial update: every field falls back to its current value, so a caller
	// sends only what changed.
	UpdateWordSense(ctx context.Context, arg UpdateWordSenseParams) (WordSense, error)
}

var _ Querier = (*Queries)(nil)
