// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
WHERE ($1::text IS NULL
        OR email     ILIKE '%' || $1::text || '%'
        OR full_name ILIKE '%' || $1::text || '%')
  AND ($2::text IS NULL      OR role = $2::text)
  AND ($3::bool IS NULL OR is_active = $3::bool)
`

type CountUsersParams struct {
	Search   *string
	Role     *string
	IsActive *bool
}

func (q *Queries) CountUsers(ctx context.Context, arg CountUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers, arg.Search, arg.Role, arg.IsActive)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, full_name, role)
VALUES ($1, $2, $3, $4)
RETURNING id, email, password_hash, full_name, role, avatar_url, is_active, email_verified_at, last_login_at, created_at, updated_at
`

type CreateUserParams struct {
	Email        string
	PasswordHash *string
	FullName     string
	Role         string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.FullName,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.AvatarUrl,
		&i.IsActive,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const emailExists = `-- name: EmailExists :one
SELECT EXISTS (SELECT 1 FROM users WHERE email = $1)
`

func (q *Queries) EmailExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, emailExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, full_name, role, avatar_url, is_active, email_verified_at, last_login_at, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.AvatarUrl,
		&i.IsActive,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, full_name, role, avatar_url, is_active, email_verified_at, last_login_at, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.AvatarUrl,
		&i.IsActive,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, password_hash, full_name, role, avatar_url, is_active, email_verified_at, last_login_at, created_at, updated_at FROM users
WHERE ($1::text IS NULL
        OR email     ILIKE '%' || $1::text || '%'
        OR full_name ILIKE '%' || $1::text || '%')
  AND ($2::text IS NULL      OR role = $2::text)
  AND ($3::bool IS NULL OR is_active = $3::bool)
ORDER BY
    CASE WHEN $4::text = 'created_at' AND $5::text = 'asc'  THEN created_at END ASC,
    CASE WHEN $4::text = 'created_at' AND $5::text = 'desc' THEN created_at END DESC,
    CASE WHEN $4::text = 'updated_at' AND $5::text = 'asc'  THEN updated_at END ASC,
    CASE WHEN $4::text = 'updated_at' AND $5::text = 'desc' THEN updated_at END DESC,
    CASE WHEN $4::text = 'email'      AND $5::text = 'asc'  THEN email END ASC,
    CASE WHEN $4::text = 'email'      AND $5::text = 'desc' THEN email END DESC,
    CASE WHEN $4::text = 'full_name'  AND $5::text = 'asc'  THEN full_name END ASC,
    CASE WHEN $4::text = 'full_name'  AND $5::text = 'desc' THEN full_name END DESC,
    id ASC
LIMIT $7::int OFFSET $6::int
`

type ListUsersParams struct {
	Search     *string
	Role       *string
	IsActive   *bool
	SortBy     string
	SortOrder  string
	PageOffset int32
	PageLimit  int32
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.Search,
		arg.Role,
		arg.IsActive,
		arg.SortBy,
		arg.SortOrder,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.FullName,
			&i.Role,
			&i.AvatarUrl,
			&i.IsActive,
			&i.EmailVerifiedAt,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markUserEmailVerified = `-- name: MarkUserEmailVerified :exec
UPDATE users SET email_verified_at = NOW() WHERE id = $1
`

func (q *Queries) MarkUserEmailVerified(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markUserEmailVerified, id)
	return err
}

const updateLastLogin = `-- name: UpdateLastLogin :exec
UPDATE users SET last_login_at = NOW() WHERE id = $1
`

func (q *Queries) UpdateLastLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateLastLogin, id)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET full_name  = COALESCE($1::text, full_name),
    avatar_url = COALESCE($2::text, avatar_url),
    role       = COALESCE($3::text, role),
    is_active  = COALESCE($4::bool, is_active)
WHERE id = $5
RETURNING id, email, password_hash, full_name, role, avatar_url, is_active, email_verified_at, last_login_at, created_at, updated_at
`

type UpdateUserParams struct {
	FullName  *string
	AvatarUrl *string
	Role      *string
	IsActive  *bool
	ID        uuid.UUID
}

// COALESCE lets a single statement act as a partial update: NULL means "leave
// this column alone", so PATCH semantics need no dynamic SQL.
func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.FullName,
		arg.AvatarUrl,
		arg.Role,
		arg.IsActive,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.AvatarUrl,
		&i.IsActive,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $2 WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID
	PasswordHash *string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}
