// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_words.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addWordToUser = `-- name: AddWordToUser :one
INSERT INTO user_words (user_id, word_id, status, notes, is_favourite)
VALUES (
    $1,
    $2,
    COALESCE($3::text, 'learning'),
    $4::text,
    COALESCE($5::bool, FALSE)
)
ON CONFLICT (user_id, word_id) DO UPDATE
    SET updated_at = user_words.updated_at
RETURNING user_id, word_id, status, notes, is_favourite, review_count, correct_count, box, last_reviewed_at, due_at, added_at, updated_at
`

type AddWordToUserParams struct {
	UserID      uuid.UUID
	WordID      uuid.UUID
	Status      *string
	Notes       *string
	IsFavourite *bool
}

// Idempotent by design: adding a word already in the list is not an error, it
// just returns the existing row untouched so the client can be naive about it.
func (q *Queries) AddWordToUser(ctx context.Context, arg AddWordToUserParams) (UserWord, error) {
	row := q.db.QueryRow(ctx, addWordToUser,
		arg.UserID,
		arg.WordID,
		arg.Status,
		arg.Notes,
		arg.IsFavourite,
	)
	var i UserWord
	err := row.Scan(
		&i.UserID,
		&i.WordID,
		&i.Status,
		&i.Notes,
		&i.IsFavourite,
		&i.ReviewCount,
		&i.CorrectCount,
		&i.Box,
		&i.LastReviewedAt,
		&i.DueAt,
		&i.AddedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countUserWords = `-- name: CountUserWords :one
SELECT COUNT(*)
FROM user_words uw
JOIN words w ON w.id = uw.word_id
WHERE uw.user_id = $1::uuid
  AND ($2::text IS NULL
        OR w.term       ILIKE '%' || $2::text || '%'
        OR w.definition ILIKE '%' || $2::text || '%')
  AND ($3::text IS NULL       OR uw.status = $3::text)
  AND ($4::text IS NULL     OR w.language = $4::text)
  AND ($5::text[] IS NULL       OR w.tags @> $5::text[])
  AND ($6::bool IS NULL OR uw.is_favourite = $6::bool)
  AND (NOT $7::bool          OR (uw.due_at <= NOW() AND uw.status <> 'archived'))
`

type CountUserWordsParams struct {
	UserID      uuid.UUID
	Search      *string
	Status      *string
	Language    *string
	Tags        []string
	IsFavourite *bool
	DueOnly     bool
}

func (q *Queries) CountUserWords(ctx context.Context, arg CountUserWordsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUserWords,
		arg.UserID,
		arg.Search,
		arg.Status,
		arg.Language,
		arg.Tags,
		arg.IsFavourite,
		arg.DueOnly,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserWord = `-- name: GetUserWord :one
SELECT user_id, word_id, status, notes, is_favourite, review_count, correct_count, box, last_reviewed_at, due_at, added_at, updated_at FROM user_words WHERE user_id = $1 AND word_id = $2
`

type GetUserWordParams struct {
	UserID uuid.UUID
	WordID uuid.UUID
}

func (q *Queries) GetUserWord(ctx context.Context, arg GetUserWordParams) (UserWord, error) {
	row := q.db.QueryRow(ctx, getUserWord, arg.UserID, arg.WordID)
	var i UserWord
	err := row.Scan(
		&i.UserID,
		&i.WordID,
		&i.Status,
		&i.Notes,
		&i.IsFavourite,
		&i.ReviewCount,
		&i.CorrectCount,
		&i.Box,
		&i.LastReviewedAt,
		&i.DueAt,
		&i.AddedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserWordStats = `-- name: GetUserWordStats :one
SELECT
    COUNT(*)::bigint                                                            AS total,
    COUNT(*) FILTER (WHERE status = 'learning')::bigint                          AS learning,
    COUNT(*) FILTER (WHERE status = 'known')::bigint                             AS known,
    COUNT(*) FILTER (WHERE status = 'archived')::bigint                          AS archived,
    COUNT(*) FILTER (WHERE is_favourite)::bigint                                 AS favourites,
    COUNT(*) FILTER (WHERE due_at <= NOW() AND status <> 'archived')::bigint      AS due,
    COALESCE(SUM(review_count), 0)::bigint                                       AS reviews,
    COALESCE(SUM(correct_count), 0)::bigint                                      AS correct
FROM user_words
WHERE user_id = $1
`

type GetUserWordStatsRow struct {
	Total      int64
	Learning   int64
	Known      int64
	Archived   int64
	Favourites int64
	Due        int64
	Reviews    int64
	Correct    int64
}

// Powers the progress header in one query rather than five counts.
func (q *Queries) GetUserWordStats(ctx context.Context, userID uuid.UUID) (GetUserWordStatsRow, error) {
	row := q.db.QueryRow(ctx, getUserWordStats, userID)
	var i GetUserWordStatsRow
	err := row.Scan(
		&i.Total,
		&i.Learning,
		&i.Known,
		&i.Archived,
		&i.Favourites,
		&i.Due,
		&i.Reviews,
		&i.Correct,
	)
	return i, err
}

const listUserWords = `-- name: ListUserWords :many
SELECT
    uw.user_id,
    uw.word_id,
    uw.status,
    uw.notes,
    uw.is_favourite,
    uw.review_count,
    uw.correct_count,
    uw.box,
    uw.last_reviewed_at,
    uw.due_at,
    uw.added_at,
    uw.updated_at,
    w.term           AS word_term,
    w.language       AS word_language,
    w.part_of_speech AS word_part_of_speech,
    w.definition     AS word_definition,
    w.example        AS word_example,
    w.pronunciation  AS word_pronunciation,
    w.tags           AS word_tags,
    w.created_by     AS word_created_by,
    w.created_at     AS word_created_at,
    w.updated_at     AS word_updated_at
FROM user_words uw
JOIN words w ON w.id = uw.word_id
WHERE uw.user_id = $1::uuid
  AND ($2::text IS NULL
        OR w.term       ILIKE '%' || $2::text || '%'
        OR w.definition ILIKE '%' || $2::text || '%')
  AND ($3::text IS NULL       OR uw.status = $3::text)
  AND ($4::text IS NULL     OR w.language = $4::text)
  AND ($5::text[] IS NULL       OR w.tags @> $5::text[])
  AND ($6::bool IS NULL OR uw.is_favourite = $6::bool)
  -- ` + "`" + `due_only` + "`" + ` selects the review queue: everything scheduled for now or past.
  AND (NOT $7::bool          OR (uw.due_at <= NOW() AND uw.status <> 'archived'))
ORDER BY
    CASE WHEN $8::text = 'added_at' AND $9::text = 'asc'  THEN uw.added_at END ASC,
    CASE WHEN $8::text = 'added_at' AND $9::text = 'desc' THEN uw.added_at END DESC,
    CASE WHEN $8::text = 'due_at'   AND $9::text = 'asc'  THEN uw.due_at END ASC,
    CASE WHEN $8::text = 'due_at'   AND $9::text = 'desc' THEN uw.due_at END DESC,
    CASE WHEN $8::text = 'term'     AND $9::text = 'asc'  THEN w.term END ASC,
    CASE WHEN $8::text = 'term'     AND $9::text = 'desc' THEN w.term END DESC,
    uw.word_id ASC
LIMIT $11::int OFFSET $10::int
`

type ListUserWordsParams struct {
	UserID      uuid.UUID
	Search      *string
	Status      *string
	Language    *string
	Tags        []string
	IsFavourite *bool
	DueOnly     bool
	SortBy      string
	SortOrder   string
	PageOffset  int32
	PageLimit   int32
}

type ListUserWordsRow struct {
	UserID            uuid.UUID
	WordID            uuid.UUID
	Status            string
	Notes             *string
	IsFavourite       bool
	ReviewCount       int32
	CorrectCount      int32
	Box               int16
	LastReviewedAt    *time.Time
	DueAt             time.Time
	AddedAt           time.Time
	UpdatedAt         time.Time
	WordTerm          string
	WordLanguage      string
	WordPartOfSpeech  *string
	WordDefinition    string
	WordExample       *string
	WordPronunciation *string
	WordTags          []string
	WordCreatedBy     pgtype.UUID
	WordCreatedAt     time.Time
	WordUpdatedAt     time.Time
}

// The list view joins the catalogue so one round trip returns everything the
// client renders. Column names are prefixed to keep them unambiguous in Go.
func (q *Queries) ListUserWords(ctx context.Context, arg ListUserWordsParams) ([]ListUserWordsRow, error) {
	rows, err := q.db.Query(ctx, listUserWords,
		arg.UserID,
		arg.Search,
		arg.Status,
		arg.Language,
		arg.Tags,
		arg.IsFavourite,
		arg.DueOnly,
		arg.SortBy,
		arg.SortOrder,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserWordsRow{}
	for rows.Next() {
		var i ListUserWordsRow
		if err := rows.Scan(
			&i.UserID,
			&i.WordID,
			&i.Status,
			&i.Notes,
			&i.IsFavourite,
			&i.ReviewCount,
			&i.CorrectCount,
			&i.Box,
			&i.LastReviewedAt,
			&i.DueAt,
			&i.AddedAt,
			&i.UpdatedAt,
			&i.WordTerm,
			&i.WordLanguage,
			&i.WordPartOfSpeech,
			&i.WordDefinition,
			&i.WordExample,
			&i.WordPronunciation,
			&i.WordTags,
			&i.WordCreatedBy,
			&i.WordCreatedAt,
			&i.WordUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordReview = `-- name: RecordReview :one
UPDATE user_words
SET review_count     = review_count + 1,
    correct_count    = correct_count + CASE WHEN $1::bool THEN 1 ELSE 0 END,
    box              = CASE WHEN $1::bool THEN LEAST(box + 1, 5) ELSE 0 END,
    status           = CASE
                           WHEN status = 'archived' THEN status
                           WHEN $1::bool AND box + 1 >= 5 THEN 'known'
                           ELSE 'learning'
                       END,
    last_reviewed_at = NOW(),
    due_at           = NOW() + (CASE
                           WHEN NOT $1::bool THEN INTERVAL '10 minutes'
                           WHEN box + 1 = 1 THEN INTERVAL '1 day'
                           WHEN box + 1 = 2 THEN INTERVAL '2 days'
                           WHEN box + 1 = 3 THEN INTERVAL '4 days'
                           WHEN box + 1 = 4 THEN INTERVAL '7 days'
                           ELSE INTERVAL '15 days'
                       END)
WHERE user_id = $2::uuid AND word_id = $3::uuid
RETURNING user_id, word_id, status, notes, is_favourite, review_count, correct_count, box, last_reviewed_at, due_at, added_at, updated_at
`

type RecordReviewParams struct {
	Correct bool
	UserID  uuid.UUID
	WordID  uuid.UUID
}

// Leitner scheduling, done in one statement so the counters and the next due
// date can never disagree. A correct answer promotes the card one box (max 5),
// a wrong answer sends it back to box 0 for same-day repetition. Intervals are
// 0d, 1d, 2d, 4d, 7d, 15d.
func (q *Queries) RecordReview(ctx context.Context, arg RecordReviewParams) (UserWord, error) {
	row := q.db.QueryRow(ctx, recordReview, arg.Correct, arg.UserID, arg.WordID)
	var i UserWord
	err := row.Scan(
		&i.UserID,
		&i.WordID,
		&i.Status,
		&i.Notes,
		&i.IsFavourite,
		&i.ReviewCount,
		&i.CorrectCount,
		&i.Box,
		&i.LastReviewedAt,
		&i.DueAt,
		&i.AddedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const removeWordFromUser = `-- name: RemoveWordFromUser :execrows
DELETE FROM user_words WHERE user_id = $1 AND word_id = $2
`

type RemoveWordFromUserParams struct {
	UserID uuid.UUID
	WordID uuid.UUID
}

func (q *Queries) RemoveWordFromUser(ctx context.Context, arg RemoveWordFromUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeWordFromUser, arg.UserID, arg.WordID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserWord = `-- name: UpdateUserWord :one
UPDATE user_words
SET status       = COALESCE($1::text, status),
    notes        = CASE WHEN $2::bool THEN NULL
                        ELSE COALESCE($3::text, notes) END,
    is_favourite = COALESCE($4::bool, is_favourite)
WHERE user_id = $5::uuid AND word_id = $6::uuid
RETURNING user_id, word_id, status, notes, is_favourite, review_count, correct_count, box, last_reviewed_at, due_at, added_at, updated_at
`

type UpdateUserWordParams struct {
	Status      *string
	ClearNotes  bool
	Notes       *string
	IsFavourite *bool
	UserID      uuid.UUID
	WordID      uuid.UUID
}

func (q *Queries) UpdateUserWord(ctx context.Context, arg UpdateUserWordParams) (UserWord, error) {
	row := q.db.QueryRow(ctx, updateUserWord,
		arg.Status,
		arg.ClearNotes,
		arg.Notes,
		arg.IsFavourite,
		arg.UserID,
		arg.WordID,
	)
	var i UserWord
	err := row.Scan(
		&i.UserID,
		&i.WordID,
		&i.Status,
		&i.Notes,
		&i.IsFavourite,
		&i.ReviewCount,
		&i.CorrectCount,
		&i.Box,
		&i.LastReviewedAt,
		&i.DueAt,
		&i.AddedAt,
		&i.UpdatedAt,
	)
	return i, err
}
