// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: word_senses.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createWordSense = `-- name: CreateWordSense :one
INSERT INTO word_senses (word_id, part_of_speech, definition, example, meta, sense_order)
VALUES (
    $1,
    $3::text,
    $2,
    $4::text,
    COALESCE($5::jsonb, '{}'::jsonb),
    $6::smallint
)
RETURNING id, word_id, part_of_speech, definition, example, meta, sense_order, created_at, updated_at
`

type CreateWordSenseParams struct {
	WordID       uuid.UUID
	Definition   string
	PartOfSpeech *string
	Example      *string
	Meta         []byte
	SenseOrder   int16
}

func (q *Queries) CreateWordSense(ctx context.Context, arg CreateWordSenseParams) (WordSense, error) {
	row := q.db.QueryRow(ctx, createWordSense,
		arg.WordID,
		arg.Definition,
		arg.PartOfSpeech,
		arg.Example,
		arg.Meta,
		arg.SenseOrder,
	)
	var i WordSense
	err := row.Scan(
		&i.ID,
		&i.WordID,
		&i.PartOfSpeech,
		&i.Definition,
		&i.Example,
		&i.Meta,
		&i.SenseOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWordSense = `-- name: DeleteWordSense :execrows
DELETE FROM word_senses WHERE id = $1
`

func (q *Queries) DeleteWordSense(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWordSense, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteWordSensesByWord = `-- name: DeleteWordSensesByWord :exec
DELETE FROM word_senses WHERE word_id = $1
`

func (q *Queries) DeleteWordSensesByWord(ctx context.Context, wordID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteWordSensesByWord, wordID)
	return err
}

const getWordSense = `-- name: GetWordSense :one
SELECT id, word_id, part_of_speech, definition, example, meta, sense_order, created_at, updated_at FROM word_senses WHERE id = $1
`

func (q *Queries) GetWordSense(ctx context.Context, id uuid.UUID) (WordSense, error) {
	row := q.db.QueryRow(ctx, getWordSense, id)
	var i WordSense
	err := row.Scan(
		&i.ID,
		&i.WordID,
		&i.PartOfSpeech,
		&i.Definition,
		&i.Example,
		&i.Meta,
		&i.SenseOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWordSensesByWord = `-- name: ListWordSensesByWord :many
SELECT id, word_id, part_of_speech, definition, example, meta, sense_order, created_at, updated_at FROM word_senses WHERE word_id = $1 ORDER BY sense_order ASC, created_at ASC
`

func (q *Queries) ListWordSensesByWord(ctx context.Context, wordID uuid.UUID) ([]WordSense, error) {
	rows, err := q.db.Query(ctx, listWordSensesByWord, wordID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WordSense{}
	for rows.Next() {
		var i WordSense
		if err := rows.Scan(
			&i.ID,
			&i.WordID,
			&i.PartOfSpeech,
			&i.Definition,
			&i.Example,
			&i.Meta,
			&i.SenseOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWordSense = `-- name: UpdateWordSense :one
UPDATE word_senses
SET part_of_speech = CASE WHEN $1::bool THEN NULL
                          ELSE COALESCE($2::text, part_of_speech) END,
    definition      = COALESCE($3::text, definition),
    example         = CASE WHEN $4::bool THEN NULL
                          ELSE COALESCE($5::text, example) END,
    meta            = COALESCE($6::jsonb, meta)
WHERE id = $7::uuid
RETURNING id, word_id, part_of_speech, definition, example, meta, sense_order, created_at, updated_at
`

type UpdateWordSenseParams struct {
	ClearPartOfSpeech bool
	PartOfSpeech      *string
	Definition        *string
	ClearExample      bool
	Example           *string
	Meta              []byte
	ID                uuid.UUID
}

// Partial update: every field falls back to its current value, so a caller
// sends only what changed.
func (q *Queries) UpdateWordSense(ctx context.Context, arg UpdateWordSenseParams) (WordSense, error) {
	row := q.db.QueryRow(ctx, updateWordSense,
		arg.ClearPartOfSpeech,
		arg.PartOfSpeech,
		arg.Definition,
		arg.ClearExample,
		arg.Example,
		arg.Meta,
		arg.ID,
	)
	var i WordSense
	err := row.Scan(
		&i.ID,
		&i.WordID,
		&i.PartOfSpeech,
		&i.Definition,
		&i.Example,
		&i.Meta,
		&i.SenseOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
