// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: words.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countWords = `-- name: CountWords :one
SELECT COUNT(*) FROM words
WHERE ($1::text IS NULL
        OR term       ILIKE '%' || $1::text || '%'
        OR definition ILIKE '%' || $1::text || '%')
  AND ($2::text IS NULL       OR language = $2::text)
  AND ($3::text IS NULL OR part_of_speech = $3::text)
  AND ($4::text[] IS NULL         OR tags @> $4::text[])
  AND ($5::uuid IS NULL     OR created_by = $5::uuid)
`

type CountWordsParams struct {
	Search       *string
	Language     *string
	PartOfSpeech *string
	Tags         []string
	CreatedBy    pgtype.UUID
}

func (q *Queries) CountWords(ctx context.Context, arg CountWordsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countWords,
		arg.Search,
		arg.Language,
		arg.PartOfSpeech,
		arg.Tags,
		arg.CreatedBy,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWord = `-- name: CreateWord :one
INSERT INTO words (term, language, part_of_speech, definition, example, pronunciation, tags, created_by)
VALUES (
    $1,
    $2,
    $4::text,
    $3,
    $5::text,
    $6::text,
    $7::text[],
    $8::uuid
)
RETURNING id, term, language, part_of_speech, definition, example, pronunciation, tags, created_by, created_at, updated_at
`

type CreateWordParams struct {
	Term          string
	Language      string
	Definition    string
	PartOfSpeech  *string
	Example       *string
	Pronunciation *string
	Tags          []string
	CreatedBy     pgtype.UUID
}

func (q *Queries) CreateWord(ctx context.Context, arg CreateWordParams) (Word, error) {
	row := q.db.QueryRow(ctx, createWord,
		arg.Term,
		arg.Language,
		arg.Definition,
		arg.PartOfSpeech,
		arg.Example,
		arg.Pronunciation,
		arg.Tags,
		arg.CreatedBy,
	)
	var i Word
	err := row.Scan(
		&i.ID,
		&i.Term,
		&i.Language,
		&i.PartOfSpeech,
		&i.Definition,
		&i.Example,
		&i.Pronunciation,
		&i.Tags,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWord = `-- name: DeleteWord :execrows
DELETE FROM words WHERE id = $1
`

func (q *Queries) DeleteWord(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWord, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getWord = `-- name: GetWord :one
SELECT id, term, language, part_of_speech, definition, example, pronunciation, tags, created_by, created_at, updated_at FROM words WHERE id = $1
`

func (q *Queries) GetWord(ctx context.Context, id uuid.UUID) (Word, error) {
	row := q.db.QueryRow(ctx, getWord, id)
	var i Word
	err := row.Scan(
		&i.ID,
		&i.Term,
		&i.Language,
		&i.PartOfSpeech,
		&i.Definition,
		&i.Example,
		&i.Pronunciation,
		&i.Tags,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWordByTerm = `-- name: GetWordByTerm :one
SELECT id, term, language, part_of_speech, definition, example, pronunciation, tags, created_by, created_at, updated_at FROM words
WHERE language = $1
  AND term = $2
  AND COALESCE(part_of_speech, '') = COALESCE($3::text, '')
`

type GetWordByTermParams struct {
	Language     string
	Term         string
	PartOfSpeech *string
}

// The natural key. COALESCE mirrors the unique index so a lookup with no part
// of speech finds the row stored without one.
func (q *Queries) GetWordByTerm(ctx context.Context, arg GetWordByTermParams) (Word, error) {
	row := q.db.QueryRow(ctx, getWordByTerm, arg.Language, arg.Term, arg.PartOfSpeech)
	var i Word
	err := row.Scan(
		&i.ID,
		&i.Term,
		&i.Language,
		&i.PartOfSpeech,
		&i.Definition,
		&i.Example,
		&i.Pronunciation,
		&i.Tags,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWordTags = `-- name: ListWordTags :many
SELECT tag, COUNT(*)::bigint AS uses
FROM words, UNNEST(tags) AS tag
WHERE ($1::text IS NULL OR language = $1::text)
GROUP BY tag
ORDER BY uses DESC, tag ASC
LIMIT $2::int
`

type ListWordTagsParams struct {
	Language  *string
	PageLimit int32
}

type ListWordTagsRow struct {
	Tag  interface{}
	Uses int64
}

// Distinct tags with usage counts, for filter menus and autocomplete.
func (q *Queries) ListWordTags(ctx context.Context, arg ListWordTagsParams) ([]ListWordTagsRow, error) {
	rows, err := q.db.Query(ctx, listWordTags, arg.Language, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWordTagsRow{}
	for rows.Next() {
		var i ListWordTagsRow
		if err := rows.Scan(&i.Tag, &i.Uses); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWords = `-- name: ListWords :many
SELECT id, term, language, part_of_speech, definition, example, pronunciation, tags, created_by, created_at, updated_at FROM words
WHERE ($1::text IS NULL
        OR term       ILIKE '%' || $1::text || '%'
        OR definition ILIKE '%' || $1::text || '%')
  AND ($2::text IS NULL       OR language = $2::text)
  AND ($3::text IS NULL OR part_of_speech = $3::text)
  -- Tag filter is a containment check, so it uses the GIN index.
  AND ($4::text[] IS NULL         OR tags @> $4::text[])
  AND ($5::uuid IS NULL     OR created_by = $5::uuid)
ORDER BY
    CASE WHEN $6::text = 'created_at' AND $7::text = 'asc'  THEN created_at END ASC,
    CASE WHEN $6::text = 'created_at' AND $7::text = 'desc' THEN created_at END DESC,
    CASE WHEN $6::text = 'updated_at' AND $7::text = 'asc'  THEN updated_at END ASC,
    CASE WHEN $6::text = 'updated_at' AND $7::text = 'desc' THEN updated_at END DESC,
    CASE WHEN $6::text = 'term'       AND $7::text = 'asc'  THEN term END ASC,
    CASE WHEN $6::text = 'term'       AND $7::text = 'desc' THEN term END DESC,
    id ASC
LIMIT $9::int OFFSET $8::int
`

type ListWordsParams struct {
	Search       *string
	Language     *string
	PartOfSpeech *string
	Tags         []string
	CreatedBy    pgtype.UUID
	SortBy       string
	SortOrder    string
	PageOffset   int32
	PageLimit    int32
}

func (q *Queries) ListWords(ctx context.Context, arg ListWordsParams) ([]Word, error) {
	rows, err := q.db.Query(ctx, listWords,
		arg.Search,
		arg.Language,
		arg.PartOfSpeech,
		arg.Tags,
		arg.CreatedBy,
		arg.SortBy,
		arg.SortOrder,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Word{}
	for rows.Next() {
		var i Word
		if err := rows.Scan(
			&i.ID,
			&i.Term,
			&i.Language,
			&i.PartOfSpeech,
			&i.Definition,
			&i.Example,
			&i.Pronunciation,
			&i.Tags,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWord = `-- name: UpdateWord :one
UPDATE words
SET term           = COALESCE($1::citext, term),
    language       = COALESCE($2::text, language),
    part_of_speech = CASE WHEN $3::bool THEN NULL
                          ELSE COALESCE($4::text, part_of_speech) END,
    definition     = COALESCE($5::text, definition),
    example        = CASE WHEN $6::bool THEN NULL
                          ELSE COALESCE($7::text, example) END,
    pronunciation  = CASE WHEN $8::bool THEN NULL
                          ELSE COALESCE($9::text, pronunciation) END,
    tags           = COALESCE($10::text[], tags)
WHERE id = $11::uuid
RETURNING id, term, language, part_of_speech, definition, example, pronunciation, tags, created_by, created_at, updated_at
`

type UpdateWordParams struct {
	Term               pgtype.Text
	Language           *string
	ClearPartOfSpeech  bool
	PartOfSpeech       *string
	Definition         *string
	ClearExample       bool
	Example            *string
	ClearPronunciation bool
	Pronunciation      *string
	Tags               []string
	ID                 uuid.UUID
}

// Partial update: every field falls back to its current value, so a caller
// sends only what changed.
func (q *Queries) UpdateWord(ctx context.Context, arg UpdateWordParams) (Word, error) {
	row := q.db.QueryRow(ctx, updateWord,
		arg.Term,
		arg.Language,
		arg.ClearPartOfSpeech,
		arg.PartOfSpeech,
		arg.Definition,
		arg.ClearExample,
		arg.Example,
		arg.ClearPronunciation,
		arg.Pronunciation,
		arg.Tags,
		arg.ID,
	)
	var i Word
	err := row.Scan(
		&i.ID,
		&i.Term,
		&i.Language,
		&i.PartOfSpeech,
		&i.Definition,
		&i.Example,
		&i.Pronunciation,
		&i.Tags,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
